services:
  janusgraph:
    image: bikashpdash/janusgraph:latest
    container_name: janusgraph
    ports:
      - "8182:8182"
    # The mounted volume only makes sense if JanusGraph is being run with the BerekeleyDB storage.

  bigtable:
    image: google/google-cloud-sdk:latest
    container_name: bigtable
    command: gcloud beta emulators bigtable start --host-port=0.0.0.0:8086
    ports:
      - "8086:8086"
