services:
  janusgraph:
    image: bikashpdash/janusgraph:latest
    container_name: janusgraph
    ports:
      - "8182:8182"
    environment:
      - BIGTABLE_EMULATOR_HOST=bigtable:8086
    volumes:
      - $PWD/janusgraph-hbase.properties:/janusgraph/conf/janusgraph-hbase.properties
    command: ["./janusgraph/bin/janusgraph-server.sh","console","conf/gremlin-server/gremlin-server-hbase.yaml"]

  bigtable:
    image: bikashpdash/gcloud-cli
    container_name: bigtable
    ports:
      - "8086:8086"
    command: gcloud beta emulators bigtable start --host-port=0.0.0.0:8086
