services:
  bigtable:
    image: bikashpdash/google-cloud-cli:latest-arm64
    container_name: bigtable
    command: gcloud beta emulators bigtable start --host-port=0.0.0.0:8086
    ports:
      - "8086:8086"